compilation_database_dir: build
output_directory: docs

diagrams:
  CompositePattern:
    type: class
    glob:
        - source/UI/Controller.cpp
        - source/UI/ontroller3D.cpp
        - source/UI/Controller2D.cpp
        - source/UI/Container2D.cpp
        - source/UI/Container3D.cpp
        - source/UI/Form.cpp
        - source/UI/Form3D.cpp
    include:
      namespaces:
        - MyBase
        - MyBase3D
