@startuml

class Controller2D {
    ..Abstract base class (from include)..
}

class Wrapper extends Controller2D {
    +Wrapper(Controller2D* controller)
    +~Wrapper()
    -Wrapper(const Wrapper&) = delete
    -Wrapper& operator=(const Wrapper&) const = delete
    +void changeState(Controller2D* controller)
    +bool isEmpty() const
    +bool isHovered() const
    +bool isReleased() const
    +bool isDoubleClick() const
    +bool isPressed() const
    +bool isMouseDown() const
    +bool isFocus() const
    +bool isVisible() const
    +void setHover(const bool& hover)
    +void setHover(const glm::vec2& position)
    +glm::vec2 getPosition() const
    +glm::vec2 getSize() const
    +void setFocus(const bool& focus)
    +void setVisible(const bool& visible)
    +void reset()
    +void update()
    +Controller2D* getState()
    #bool contains(const glm::vec2& position) const
    #bool catchEvent(GLFWwindow* window)
    #bool handle(GLFWwindow* window)
    #void glDraw() const
    #void glDrawTransparent() const
    -Controller2D* __controller
}

@enduml
