// ĐẶT CÁC MACRO Ở ĐÂY TRƯỚC KHI INCLUDE
#define TINYGLTF_IMPLEMENTATION
#define STB_IMAGE_IMPLEMENTATION 
#define STB_IMAGE_WRITE_IMPLEMENTATION
#define STBI_MSC_SECURE_CRT
// Không cần include config.h ở đây